### ISSUE TITLE
Seem pin not match with image

### ISSUE THREAD

**Issue by LabFnP** [Nikolay-Kha/PyCNC#17]
![2018-01-31 12 17 04](https://user-images.githubusercontent.com/34938469/35605031-d3ba8f94-0680-11e8-8f32-d1bf9c8a8203.png)
Seem the D34 should be D30? I find it does not match with your image (https://user-images.githubusercontent.com/8740775/28233650-d64060e0-6900-11e7-8605-6475384fd2f7.png)

**Comment by Nikolay-Kha** [comment]
That's right. Thank you!
