### ISSUE TITLE
extruder motor

### ISSUE THREAD

**Issue by hmovahedim** [Nikolay-Kha/PyCNC#19]
hello
i installed extruder motor on ramps and ran pycnc when i typed command ( m104 s220 ) raspberry pi turned on extruder but extruder motor not working .

**Comment by Nikolay-Kha** [comment]
Hi,
m104 command enables heater only. To move extruder motor you need to move E axis.
For example g1e1 command.

**Comment by hmovahedim** [comment]
thanks nikolay
