### ISSUE TITLE
reusing to revive a CNC machine

### ISSUE THREAD

**Issue by BMaxV** [Nikolay-Kha/PyCNC#27]
Hey, 

I have a relatively big CNC machine in the basement, all the hardware is present but I've given up on configuring it correctly with linuxcnc.

The drivers are Leadshine Microstep m542 s

They already have some neat cables so I was thinking all I would have to do to make this work is change some pin numbers.

Will pyCNC automatically detect that I don't have a heatbed, etc.? How does calibration work, to make sure it doesn't run out of bounds?

**Comment by Nikolay-Kha** [comment]
PyCNC knows only pin number which should be triggered if command for heatbed is provided. So calibration and anything else should work without heatbed.
Calibration simply moves steppers slowly and check if endpoint switch was triggered. If so, stops moving. Endpoint switches pin can be configured in a config.
