### ISSUE TITLE
How to test if my setup works?

### ISSUE THREAD

**Issue by janoist1** [Nikolay-Kha/PyCNC#41]
Hi,
I'm very excited about this project! I have rebuilt my chinese Anet a8 printer according to the article. When I feed a gcode file to `pycnc` the printer starts to do things: making some beep-beep noise as well as heating the bed then the extruder head. And this is pretty much the progress it has done so far. I've got some questions:
- how to test each axis in `pycnc` shell?
- how to set "home" all 3 axis? I used to have an option in Merlin's menu something like "home" which aligned things to start position.

Many thanks!

**Comment by Nikolay-Kha** [comment]
Hello!
run pycnc in the terminal and use regular gcode.
g1x100 for example to move x only axis.
g28 to move all axis to home position.

**Comment by janoist1** [comment]
Hi! Thanks @Nikolay-Kha  for the answer. I have managed to move the Y axis, however none of the rest seem to work. I have double checked all the wires as well as replaced the Ramps with another one due to a previous burnout of the steppers (put in wrong direction).
When I simply swap the X - Y axis wires I can see the motors working.
Have you got any idea what's going wrong? Or please give me some advices on how to debug it. I've not been able to use my printer for ages now.
Many thanks!
Update: When I start `pycnc` only the Y axis flexing, other motors are not doing anything.
Also, swapping of servos won't make any difference.
