### ISSUE TITLE
Z motors don't work

### ISSUE THREAD

**Issue by janoist1** [Nikolay-Kha/PyCNC#43]
Hi,
I'm testing my setup using raw g code commands, like z10.
Z motors don't seem to work, they only make some whistle-like sound when supposed to be moving. I have tried with different steppers and motors too. Different stepper driver does the same issue, wiring to different motors also same. Just buzzing/screaming.
Any idea?
I can't wait for this working on my desk... 🙏

A video showing what happens when running `g28`:
https://photos.app.goo.gl/CoAF6Atj1Cdkjohi7

**Comment by janoist1** [comment]
Ok, I have managed to make the Z work! Had to adjust the pulse `STEPPER_PULSES_PER_MM_Z` down to 50. I'm not sure what it exactly does or how it affects the end print quality. 🤷‍♂️

**Comment by janoist1** [comment]
Now the question is, how to calculate the config values for my printer? Unfortunately the motors spin too fast, especially the extruder motor. Thanks!

**Comment by Nikolay-Kha** [comment]
> how to calculate the config values for my printer?
Find specs for your hardware. Or calculate these values according to your construction. Or do some empirical tests - commands have values in millimeters, compare it with actual physical distance of axis and adjust parameters.
