### ISSUE TITLE
Only works Y-axis

### ISSUE THREAD

**Issue by rodrigoVM8** [Nikolay-Kha/PyCNC#46]
I was trying to run commands like G1 X100 , G1 Y100 or G1 Z100 , but only works with Y axis. All the parameters in config file are the same for X, Y and Z axis. The enable pin is working too. I dont know what could be the problem. Help please.

**Comment by Nikolay-Kha** [comment]
Check presence of pulses on STEP pins of all motor drivers. You can do it with oscilloscope / logic analyzer or simply visually with LED(it should blink with very short lights).

**Comment by rodrigoVM8** [comment]
Thanks a lot, i was having trouble with my enable pin, i needed high level for that
