### ISSUE TITLE
How to achieve the maximum velocity for Z axis

### ISSUE THREAD

**Issue by rodrigoVM8** [Nikolay-Kha/PyCNC#49]
Hi Nikolay, i need to achieve the maximum velocity for Z axis (NEMA 23). my driver is set for 200 Pulses/rev. I've tried changing the config file, but when i try to increase MAX_VELOCITY_MM_PER_MIN_Z my stepper motor stops working and make weird noises. im trying to make an embroidery machine, and i using Z axis for the stitches, thats why Zaxis must need a lot faster than X and Y axis.
Need your help.
Thanks.

**Comment by Nikolay-Kha** [comment]
Hi, to achieve maximum velocity, especially if moments quite short(i don't think you move z axis more than a couple of centimeters to do stitches) you need to have big acceleration, to accelerate motor properly. If you apply pulse at max velocity without accelerating motor - I'll get noise. And I believe you experience that. Try to play with STEPPER_MAX_ACCELERATION_MM_PER_S2 parameter from config file.
